version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.49
    steps:
      - checkout
      - run: make build
      - persist_to_workspace:
          root: .
          paths: public

  deploy:
    docker:
      - image: circleci/python:2.7-jessie

    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: public
      - run: sudo pip install awscli
      - run: sudo apt-get install -y make curl && make publish

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master